export default {
    "lets book": "LET'S BOOK",
    "bayt salwa": "BAYT SALWA",
    gal: "GAL",
    lery: "LERY",
    reach: "REACH",
    us: "US",
    back: "back",
    "language change": "عربي",
    "select date": "Select Date",
    "check in": "Check In",
    "check out": "Check Out",
    "# of people": "# of People",
    "full name": "Full Name",
    "phone #": "Phone #",
    "upload photo id": "Upload Photo ID",
    "id explanation": "a proof of ID is useful to confirm legal information",
    "contract agreement": "Contract Agreement",
    "book now": "Book Now",
    "contract-1": "Bayt Salwa is renting out an accomadation to",
    "contract-2": "On the following address:",
    "contract-3": "Zawtar al Sharkeyeh,",
    "contract-4": "Nahr Al Leetani,",
    "contract-5": "Bayt Salwa,",
    "contract-6": "With Check-in date:",
    "contract-7": "and Check-out date:",
    "contract-8": "Guest will be responsible for ensuring that the accommodation is left the same condition as it was in upon check-in",
    "contract-9": "Guest shall be liable for any damages cuased by his or her own acts and omissions (including and wihout limitation, failure to timely vacate the accomadation). and also for the acts and omissions of any individuals that Guest invites or otherwise allows into the accommodation.",
    "contract-10": "Additionally, Guest shall comply with the following requests and/or instructions:",
    "contract-list-1": "Turn off heat/cooling before checking out",
    "contract-list-2": "Lock all doors and windows before checking out",
    "contract-list-3": "Number of people should match what's included in the agreement",
    "contract-list-4": "Key return instructions *",
    "contract-list-5": "Replace any consumption items used in the cabin *",
    "contract-list-6": "Replace or compensate any broken/damaged items in the cabin",
    "agree": "I Agree",
    "disagree": "I Disagree",
};
