export default {
    "lets book": "LET'S BOOK",
    "bayt salwa": "BAYT SALWA",
    gal: "GAL",
    lery: "LERY",
    reach: "REACH",
    us: "US",
    back: "back",
    "language change": "عربي",
    "select date": "Select Date",
    "check in": "Check In",
    "check out": "Check Out",
    "# of people": "# of People",
    "full name": "Full Name",
    "phone #": "Phone #",
    "upload photo id": "Upload Photo ID",
    "id explanation": "a proof of ID is useful to confirm legal information",
    "contract agreement": "Contract Agreement",
    "book now": "Book Now",
    "contract-1": "Bayt Salwa is renting out an accomadation to",
    "contract-2": "On the following address:",
    "contract-3": "Zawtar al Sharkeyeh,",
    "contract-4": "Nahr Al Leetani,",
    "contract-5": "Bayt Salwa,",
    "contract-6": "With Check-in date:",
    "contract-7": "and Check-out date:",
    "contract-8": "Guest will be responsible for ensuring that the accommodation is left the same condition as it was in upon check-in",
    "contract-9": "Guest shall be liable for any damages cuased by his or her own acts and omissions (including and wihout limitation, failure to timely vacate the accomadation). and also for the acts and omissions of any individuals that Guest invites or otherwise allows into the accommodation.",
    "contract-10": "Additionally, Guest shall comply with the following requests and/or instructions:",
    "contract-list-1": "Turn off heat/cooling before checking out",
    "contract-list-2": "Lock all doors and windows and turn all lights off before checking out",
    "contract-list-3": "Number of people should match what's included in the agreement",
    "contract-list-4": "Take shoes off before going inside the cabin",
    "contract-list-5": "Quite time after 11:00 PM",
    "contract-list-6": "The cabin is NOT pet friendly",
    "agree": "I Agree",
    "disagree": "I Disagree",
    "terms": "I've read all terms and conditions",
    "the name": "The Name",
    "the built": "How Was it Built?",
    "the activities": "Activities, Hikes, & Adventures",
    "the things": "Things We Have In-House",
    "the visit": "Plan Your Visit",
    "the name description": "Bayt in Arabic means home. Salwa means having pleasure, fun, and chill. The origins come from the owner of the property Salwa who has the personality as the cabin itself. Bayt Salwa is where any person will find peace and happiness. The sound of the water smashing the rocks in a quite night is so calm and during some nights, the howl of the wind is loud and loud. Other nights, it's the howl of the small wolves far far away. I don't want to lie, it's a bit scary but make sure that you are safe.",
    "the built description": "It was an empty lot for many years because cars couldn't get in and it would take a long time to walk to the place. After the expension of the village and when some other houses started to be built, Bayt Salwa was born. The cabin itself is a pre-fabricated container embedded in the mountain and then additional rooms where added. The architect who had the vision about the whole process was Jana; Salwa's daughter. Jana is an Interior Architect who has great visions and a huge passion for natural architecture. She's also an artist. The cabin itself is a getaway to family as well where they chill some weekends far from cars, pollution, and the loud cities.",
    "activities-title-0": "Ruins in Zawtar al Sharkeyeh",
    "activities-0": "The ruins in Zawtar El Charkieh are a continuation and extension of those in the neighboring town, Zawtar El Gharbieh. On the southern slopes, there are some natural caves, the most noteworthy being Sawda Cave and Sakkatah Cave. The latter extends to around 50 meters inwards; both caves add a beautiful natural scenery to the landscape. An old mosque stands in the town and dates back to 1850 CE.",
    "best-moment": "Your best moments in the best cabin",
    "contact-1": "CANT FIND A DATE TO BOOK?",
    "contact-2": "REFER FAMILY OR FRIENDS",
    "contact-3": "DISCOVER MORE FROM US",
    "contact-4": "CANCEL YOUR BOOKING",
};
